# Generated by Django 3.1.6 on 2021-05-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Css',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=200, null=True)),
                ('ans1', models.CharField(max_length=300, null=True)),
                ('ans2', models.CharField(max_length=300, null=True)),
                ('ans3', models.CharField(max_length=300, null=True)),
                ('ans4', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dotnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=200, null=True)),
                ('ans1', models.CharField(max_length=300, null=True)),
                ('ans2', models.CharField(max_length=300, null=True)),
                ('ans3', models.CharField(max_length=300, null=True)),
                ('ans4', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Html',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=200, null=True)),
                ('ans1', models.CharField(max_length=300, null=True)),
                ('ans2', models.CharField(max_length=300, null=True)),
                ('ans3', models.CharField(max_length=300, null=True)),
                ('ans4', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Java',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=200, null=True)),
                ('ans1', models.CharField(max_length=300, null=True)),
                ('ans2', models.CharField(max_length=300, null=True)),
                ('ans3', models.CharField(max_length=300, null=True)),
                ('ans4', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
