# Generated by Django 3.1.6 on 2021-05-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=300)),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Css',
        ),
        migrations.DeleteModel(
            name='Dotnet',
        ),
        migrations.DeleteModel(
            name='Html',
        ),
        migrations.DeleteModel(
            name='Java',
        ),
        migrations.DeleteModel(
            name='Python',
        ),
    ]
