# Generated by Django 3.1.6 on 2021-05-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20210503_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
