# Generated by Django 3.1.6 on 2021-05-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_questions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='ans',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
