# Generated by Django 3.1.6 on 2021-05-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_questions_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='atopic',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
