# Generated by Django 3.1.6 on 2021-05-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpful',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(max_length=200, null=True)),
                ('num2', models.IntegerField(max_length=200, null=True)),
                ('numid', models.IntegerField(max_length=200, null=True)),
            ],
        ),
    ]
