# Generated by Django 3.1.6 on 2021-05-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0010_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='h',
            field=models.IntegerField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='nh',
            field=models.IntegerField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
