# Generated by Django 3.1.6 on 2021-05-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0011_auto_20210522_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='ans',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='atopic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='h',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='nh',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='que',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='topic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
